env:
    SYSDIG_SECURE_ENDPOINT: "https://eu1.app.sysdig.com"
    REGISTRY_HOST: "docker.io"
    IMAGE_NAME: "pythonapp"
    IMAGE_TAG: "v1"
    
name: Container build, scan and push
on: [push, pull_request]

jobs:
  build-scan-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Build and push
      uses: docker/build-push-action@v6.2.0
      with:
       load: true
       tags: naveenrk/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

       
    - name: Download sysdig-cli-scanner if needed
      run:  |
         curl -sLO https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt
         mkdir -p ${GITHUB_WORKSPACE}/cache/db/
         if [ ! -f ${GITHUB_WORKSPACE}/cache/latest_version.txt ] || [ $(cat ./latest_version.txt) != $(cat ${GITHUB_WORKSPACE}/cache/latest_v
         cp ./latest_version.txt ${GITHUB_WORKSPACE}/cache/latest_version.txt
         curl -sL -o ${GITHUB_WORKSPACE}/cache/sysdig-cli-scanner "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(cat ${GITHU
         chmod +x ${GITHUB_WORKSPACE}/cache/sysdig-cli-scanner
         else
         echo "sysdig-cli-scanner latest version already downloaded"
         fi   
 
 
    - name: Setup cache
      uses: actions/cache@v3
      with:
       path: cache
       key: ${{ runner.os }}-cache-${{ hashFiles('**/sysdig-cli-scanner', '**/latest_version.txt', '**/db/main.db.meta.json', '**/scanner-ca
       restore-keys: ${{ runner.os }}-cache-
      
    - name: Scan the image using sysdig-cli-scanner
      env:
       SECURE_API_TOKEN: ${{ secrets.SECURE_API_TOKEN }}
      run: |
       ${GITHUB_WORKSPACE}/cache/sysdig-cli-scanner \
       --apiurl ${SYSDIG_SECURE_ENDPOINT} \
       docker://${REGISTRY_HOST}/${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${IMAGE_TAG} \
       --console-log \
       --dbpath=${GITHUB_WORKSPACE}/cache/db/ \
       --cachepath=${GITHUB_WORKSPACE}/cache/scanner-cache/    
