env:
    SYSDIG_SECURE_ENDPOINT: "https://eu1.app.sysdig.com"
    REGISTRY_HOST: "docker.io"
    IMAGE_NAME: "pythonapp"
    IMAGE_TAG: "v1"
    
name: Container build, scan and push
on: [push, pull_request]

jobs:
  build-scan-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Build and push
      uses: docker/build-push-action@v6.2.0
      with:
       load: true
       tags: naveenrk/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
       run:  docker image ls && docker container ls
